### ISSUE TITLE
safeQueue html: improve configuration screens

### ISSUE THREAD

**Issue by gfcittolin** [netsmarttech/node-red-contrib-safe-queue#42]
* Queue config
  - Choose better icons
  - Use a spinner for the timeout
  - Add time unit for timeout (ms)
  - Add a description for the configuration options
* Queue control
  - Set a default operation

**Comment by DiegoRampim** [comment]
[#43] Implementado outro tipo de input para o campo `TimeOut ACK` e adiciona a notação `ms`.
 `<input type="number" id="node-config-input-timeoutAck" min="0"> ms`

**Comment by DiegoRampim** [comment]
[#34] Definido padrão das funcionalidades do `SafeQueue Control`.
`operation: {
	value: "queue-size"
} `
